import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< HEAD
import "@/styles/globals.css";
import Header from "@/components/header";
import { Providers } from './providers';
=======
import "./globals.css";
>>>>>>> b028cd2 (refactor(front-web): front-web 폴더 제거, README 파일 제목 수정)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "KTB6 Team Blog",
  description: "Generated by Next.js",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> b028cd2 (refactor(front-web): front-web 폴더 제거, README 파일 제목 수정)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="text-gray-800 dark:text-slate-100 dark:bg-gray-900"><Providers>
          <Header />
          <main>{children}</main>
          </Providers></div>
        
      </body>
=======
    <html lang="en">
      <body className={inter.className}>{children}</body>
>>>>>>> b028cd2 (refactor(front-web): front-web 폴더 제거, README 파일 제목 수정)
    </html>
  );
}
