import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/header";
import { Providers } from './providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KTB6 Team Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="text-gray-800 dark:text-slate-100 dark:bg-gray-900"><Providers>
          <Header />
          <main>{children}</main>
          </Providers></div>
        
      </body>
    </html>
  );
}
